In [5]:
import numpy as np
arr = np.identity(3)
new_arr = arr*9
print(new_arr)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


In [10]:
import numpy as np
arr = np.arange(2,34,2)
new_arr = arr.reshape(4,4)
# print(new_arr)
mean = np.mean(arr)
standard_deviation = np.std(arr)
limit1= mean-0.5*standard_deviation
limit2=mean+0.5*standard_deviation
new_arr = arr[(arr >= limit1) & (arr <= limit2)]
print(new_arr)

[14 16 18 20]


In [14]:
import numpy as np
arr = np.full((9,9),0)
print(arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [22]:
import numpy as np
n = int(input())
arr = np.full((n,n),0)
for i in range(n):
    arr[:,i]=i+1
print(arr)

 12


[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]]
